// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCore.Entity
{
    public partial class Login
    {
        public Login()
        {
            PersonDetails = new HashSet<PersonDetails>();
        }

        public int New_Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<PersonDetails> PersonDetails { get; set; }
    }
}